### PR TITLE
Mobile (small screen) compatibility

### PR DESCRIPTION
**Pull request by DimuthuLakmal**
CSS corrections were added to bootstrap.min.css file

See #32.

### CODE REVIEW

**Comment by asamalik** [comment]
The bootstrap.css is taken from upstream and should remain unchanged. Any change to css should be done in the [/css/main.scss](https://github.com/developer-portal/website/blob/master/css/main.scss) file.

Could you please move your changes in the [/css/main.scss](https://github.com/developer-portal/website/blob/master/css/main.scss) file?

**Comment by phracek** [comment]
@DimuthuLakmal Can you please update your PR as @asamalik mentioned? THX

**Comment by pvalena** [comment]
Also, please avoid changing file permissions:

100755 → 100644

**Comment by jackorp** [comment]
Ping... @DimuthuLakmal Are you still interested in advancing with this PR?

**Comment by jackorp** [comment]
Closed for inactivity.

**Pull request closed without merging**
