### PR TITLE
Added table styles

### PR DESCRIPTION
**Pull request by RheaAyase**
ref #60

### CODE REVIEW

**Comment by pvalena** [comment]
Seems like a lot of modifications, but let's give it a try :).

**Comment by RheaAyase** [comment]
Well the "mixins" file can be cut shorter only to the specific functions... i've no idea how does it work, but I consider it a library so i've thrown the whole thing in... (btw I'll get back to the docs and stuff to finish this within a week...too much to catch up with after the conferences right now)

**Comment by pvalena** [comment]
```
[ . . . ]
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
                    Undefined mixin 'transition'. on line 235
jekyll 3.7.2 | Error:  Undefined mixin 'transition'. on line 235
```

**Comment by pvalena** [comment]
Please try to resolve this issue locally first.

**Comment by RheaAyase** [comment]
It works locally, that's the joke.

**Comment by pvalena** [comment]
In that case I am very sorry. Could you help me to figure out why does it not build?

**Comment by RheaAyase** [comment]
The thing is in the way things are being imported, found out what's the magic...

**Pull request merged**
