### PR TITLE
Add the actual logo for secondary_architectures

### PR DESCRIPTION
**Pull request by ojn**
this image was created by combining two public domain images from publicdomainvectors.org

Secondary architectures - logo

### CODE REVIEW

**Comment by pvalena** [comment]
Thanks!

Could you please paste a link to the actual source?

**Comment by ojn** [comment]
Based on this these 2 images:

https://publicdomainvectors.org/en/free-clipart/Server-database-icon-vector-image/13590.html
https://publicdomainvectors.org/en/free-clipart/Generic-computer-chip-vector-image/13455.html

it's sad that openclipart page is gone

**Comment by ojn** [comment]
svg file: https://github.com/ojn/website/blob/svg/static/logo/svg/secondary_architectures.svg
if it needs tweaking

**Comment by pvalena** [comment]
Thanks!

**Pull request merged**
