### PR TITLE
Enhance Dockerfile, and fix builds

### PR DESCRIPTION
**Pull request by pvalena**
also fix permissions.

### CODE REVIEW

**Comment by pvalena** [comment]
FWIW there's a working Dockerfile, but there's `Layout` missing still, so no Layout's are actually used (I'm not sure why), and the generated website is unusable.

https://gist.github.com/510c4b0110b37fc991708a17546738de

**Comment by pvalena** [comment]
The layouts are not properly localized, this is most probably due to missing / incompatible `theme`: https://git.io/JkhgE

**Comment by jackorp** [comment]
I have an update on the content not rendering.

Disabling jekyll-lunr-js-search (commenting it out in _config.yml and deleting the file in _plugins) makes the site compile correctly with styling. And looking on the repo it went [unmaintained in 2018](https://github.com/slashdotdash/jekyll-lunr-js-search/issues/128); there seems to be a fork: [jekyll-lunr-js-custom-search](https://github.com/dnoneill/jekyll-lunr-js-custom-search) but it does not seem to maintain compatibility i.e. current `lunr_seach:` config in `_config.yml` does not work (and the site build spews layout errors again)

**Comment by pvalena** [comment]
> I have an update on the content not rendering.
> 
> Disabling jekyll-lunr-js-search (commenting it out in _config.yml and deleting the file in _plugins) makes the site compile correctly with styling. And looking on the repo it went [unmaintained in 2018](https://github.com/slashdotdash/jekyll-lunr-js-search/issues/128); there seems to be a fork: [jekyll-lunr-js-custom-search](https://github.com/dnoneill/jekyll-lunr-js-custom-search) but it does not seem to maintain compatibility i.e. current `lunr_seach:` config in `_config.yml` does not work (and the site build spews layout errors again)

Thanks! I'll make the build without the search then.

**Comment by pvalena** [comment]
@jackorp PTAL.

**Pull request merged**
